#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
	alias $command="sudo $command"
done; unset command

se() { cd ~/.local/bin; $EDITOR $(fzf) ;}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \

# Colorize commands when possible.
alias \
	grep="grep --color=auto" \
	egrep="egrep --color=auto" \
	pgrep="pgrep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	sdn="shutdown -h now" \
  df="df -h" \
  free="free -m" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	za="zathura" \
	nf="neofetch" \
	lf="lfub" \
	sxiv="nsxiv" \
	py="python" \
	cl="clear" \
 	jctl="sudo journalctl -p 3 -xb" \
 	yt_music="yt-dlp -f 'ba' -x --audio-format mp3  -o '~/Music/%(title)s.%(ext)s'" \
 	cks="jctl && sudo dmesg | grep error && sudo systemctl --failed" \
 	startsys="sudo systemctl start" \
 	stopsys="sudo systemctl stop" \
 	ensys="sudo systemctl enable" \
 	stsys="sudo systemctl status" \
  resys="sudo systemctl restart" \
  myip="curl http://ipecho.net/plain; echo" \
  battery="upower -i `upower -e | grep 'BAT'`" \
  savermode="batterySaverMode.py" \
  news="newsboat" \
  testnet="curl -Lso- bench.sh | bash" \
	# pkgfile --update

# Replacement ls
alias \
	l="exa -FG --color=automatic --group-directories-first" \
	ll="exa -Fl --color=automatic --group-directories-first --icons --git" \
 	la="l -a" \
 	lla="ll -a" \
 	lt="tree -C --dirsfirst -L" \

# Merge Xresources
alias merge="xrdb -merge ~/.Xresources"

# Pacman and Yay
alias \
  pi="p -S --needed" \
  yi="yay -S --needed" \
	bpkg="pacman -Slq | fzf --preview 'pacman -Si {}' --layout=reverse" \
  cleanup="p -Qqd | p -Rsu - && p -Sc --noconfirm && yay -Sc --aur --noconfirm && paccache -ruk0" \

# Edit config file
alias \
  trc="nvim ~/.config/alacritty/alacritty.yml" \
  zrc="nvim $ZDOTDIR/.zshrc" \
  reloads="source $ZDOTDIR/.zshrc" \
  alrc="nvim $ZDOTDIR/aliasrc" \
  lfrc="nvim $XDG_CONFIG_HOME/lf/lfrc" \
  zarc="nvim $XDG_CONFIG_HOME/zathura/zathurarc" \
  vimrc="nvim $XDG_CONFIG_HOME/nvim/lua/base.lua" \
  mrrc="sudo -e /etc/pacman.d/mirrorlist" \

# Web development
alias \
	webon="startsys httpd.service mariadb.service" \
	weboff="stopsys httpd.service mariadb.service" \
	reweb="resys httpd.service" \
  webst="stsys mariadb httpd" \
  mgdb="startsys mongodb.service" \

# Git command
alias \
  gcl="git clone" \
  gs="git status" \
  ga="git add" \
  gp="git push" \
  gpo="git push origin" \
  gtd="git tag --delete" \
  gtdr='git tag --delete origin' \
  gr='git branch -r' \
  gplo='git pull origin' \
  gb='git branch' \
  gc='git commit' \
  gd='git diff' \
  gco='git checkout' \
  gl='git log' \
  gr='git remote' \
  grs='git remote show' \

